### ISSUE TITLE
搜索界面是否可以采用空间利用率更高的左右分屏的模式

### ISSUE THREAD

**Issue by AugustTuan** [luckept/vert#3]
现在是以前传统的上下分屏的方式，搜索目标文档的显示非常有限。
希望可以采用 dark+、Tsundoku等主题使用的左右分屏的模式。空间利用率要好很多。

![OHTODTFN)(4UX77`N2XYTXK](https://user-images.githubusercontent.com/37429029/170872549-e7312a5a-bc37-462f-abc8-50eb4c664df8.png)
![8HK3D0{_($K}42JV$2ZAT4](https://user-images.githubusercontent.com/37429029/170872556-dfcffdaf-1ec2-4ef5-a9fc-03a4d6dde3c4.png)

**Comment by luckept** [comment]
感谢建议，下个版本加上～
