### ISSUE TITLE
拖动条不显眼，看得眼睛流眼泪

### ISSUE THREAD

**Issue by AugustTuan** [luckept/vert#8]
![image](https://user-images.githubusercontent.com/37429029/171585804-dbeedd91-7eb6-4a91-914b-c2ffe82fe79d.png)

**Comment by luckept** [comment]
放假看看改改，当时临时配置了一下颜色

**Comment by AugustTuan** [comment]
> 放假看看改改，当时临时配置了一下颜色

平常这个颜色其实挺好的，相当于隐身了，无感阅读。 
就是拖动的时候能高亮就好了。（不是前端，不知道能不能实现😂

**Comment by luckept** [comment]
> > 放假看看改改，当时临时配置了一下颜色
> 
> 平常这个颜色其实挺好的，相当于隐身了，无感阅读。 就是拖动的时候能高亮就好了。（不是前端，不知道能不能实现😂

可以的
